events {}
http {
    server {
        listen      80;
        server_name localhost 127.0.0.1;

        location / {
            root    /home;
            index   index.html;
        }
    }

    server {
        listen 8000;
        server_name python;

        location / {
            proxy_pass http://python:8000/;
        }
    }

    server {
        listen 11434;
        server_name ollama;
        
        location / {
            proxy_pass http://ollama:11434/;
        }
    }
}
