# lista modelos
curl https://tseiiti.duckdns.org:11434/api/tags -H "Accept: application/json"

# lista modelos em execução
curl https://tseiiti.duckdns.org:11434/api/ps -H "Accept: application/json"

# ativa um modelo
curl -X POST https://tseiiti.duckdns.org:11434/api/chat -H "Content-Type: application/json" -d "{ \"model\": \"gemma3:1b\", \"prompt\": \"\" }"

# desativa um modelo
curl -X POST https://tseiiti.duckdns.org:11434/api/generate -H "Content-Type: application/json" -d "{ \"model\": \"gemma3:1b\", \"keep_alive\": 0 }"

curl -X POST https://tseiiti.duckdns.org:11434/api/chat -H "Content-Type: application/json" -d "{ \"model\": \"gemma3:1b\", \"prompt\": \"o que é o cálculo O.E.E?\" }"

###

GET  http://localhost:11434/api/tags

###

POST http://localhost:11434/api/generate

{
  "model": "gemma3:1b",
  "prompt": "como são os ambientes?"
}

###

POST http://localhost:11434/api/chat

{
  "model": "gemma3:1b",
  "messages": [{
    "role": "user",
    "content": "o que é a declaração de nova delhi?"
  }]
}


###

POST http://localhost:8000/context
Content-Type: application/json

{
  "query": "o que é a declaração de nova déli?",
  "file": "teste.pdf",
  "score": 1.2
}

###

POST http://localhost:8000/query
Content-Type: application/json

{
  "query": "dê mais detalhes"
}

###

GET  http://localhost:8000/models


###

POST http://localhost:8000/chat
Content-Type: application/json

{
  "model": "gemma3:1b",
  "messages": [{
    "role": "user",
    "content": "o que é a declaração de nova delhi?"
  }],
  "stream": true
}

###

POST http://localhost:8000/context
Content-Type: application/json

{
  "query": "o que é a declaração de nova delhi?"
}

###

POST http://localhost:11434/api/chat

{
  "model": "gemma3:1b",
  "messages": [{
    "role": "user",
    "content": "oi"
  }]
}

###

POST http://localhost:11434/api/chat

{
  "model": "qwen3.5:2b",
  "messages": [
    { "role": "system", "content": "\nVocê é um assistente especialista em processamento de linguagem natural e estruturação de dados.\nSua tarefa é analisar o nome completo fornecido e separá-lo em um objeto JSON com as chaves: \"primeiro_nome\", \"nome_do_meio\" e \"sobrenome\".\n\n\nRegras:\n1. Se não houver nome do meio, defina \"nome_do_meio\" como null ou uma string vazia \"\".\n2. O sobrenome é o último elemento.\n3. Responda APENAS com o JSON, sem texto explicativo antes ou depois.\n4. Os nomes serão sempre do Brasil.\n5. A CONCATENAÇÃO DOS VALORES DO PRIMEIRO_NOME, NOME_DO_MEIO E SOBRENOME DO JSON DEVEM CORRESPONDER AO NOME COMPLETO.\n\nFormato JSON esperado:\n{\n  \"primeiro_nome\": \"string\",\n  \"nome_do_meio\": \"string ou null\",\n  \"sobrenome\": \"string\"\n}\n" },
    { "role": "user", "content": "nome completo: Erika Cristina Fernandes Santos" }
  ],
  "options": {
    "temperature": 0.3
  },
  "stream": false
}