worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;

	gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript font/woff2 image/png;

    server {
        server_name tseiiti.duckdns.org projeto-integrador-6.vercel.app 192.168.*.* 172.*.*.* localhost;

        listen      80;
        listen [::]:80;
        
        # proxy_buffering off;
        # proxy_cache off;
        # proxy_set_header X-Accel-Buffering no;
        
        # location / {
        #     root    /home;
        #     index   index.html;
        # }
        
        location / {
            proxy_pass http://react:80/;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }

    server {
        server_name tseiiti.duckdns.org projeto-integrador-6.vercel.app 192.168.*.* localhost;

        listen      8000;
        listen [::]:8000;

        location / {
            proxy_pass http://python:8000/;
        }
    }

    server {
        server_name tseiiti.duckdns.org projeto-integrador-6.vercel.app 192.168.*.* localhost;

        listen      11434;
        listen [::]:11434;

        proxy_buffering off;
        proxy_cache off;
        proxy_set_header X-Accel-Buffering no;

        location / {
            proxy_pass http://ollama:11434/;
        }
    }
}
